src/Entity/Demande.php
<?php

namespace App\Entity;

use App\Repository\DemandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DemandeRepository::class)]
class Demande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 128)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $piece_jointe = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\ManyToOne(inversedBy: 'demandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Status $status = null;

    #[ORM\ManyToOne(inversedBy: 'demandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getPieceJointe(): ?string
    {
        return $this->piece_jointe;
    }

    public function setPieceJointe(?string $piece_jointe): self
    {
        $this->piece_jointe = $piece_jointe;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/DemandeType.php
<?php

namespace App\Form;

use App\Entity\Demande;
use App\Entity\Status;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DemandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'required' => true
            ])
            ->add('contenu',TextType::class, [
                'required' => true
            ])
            ->add('piece_jointe', FileType::class, [
                'label' => 'Piece jointe',
                'mapped' => false,
                'required' => true,
            ])
            ->add('status', EntityType::class, [
                'class' => Status::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.id', 'ASC')
                        ->setMaxResults(1);
                },
                'choice_label' => 'nom',
            ]) ->add('submit', SubmitType::class, [
                'label' => "Valider ma demande",
                'attr' => [
                    'class' => 'btn btn-info'
                ]
            ]);;
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Demande::class,
        ]);
    }
}

src/Controller/DemandeController.php
<?php

namespace App\Controller;

use App\Entity\Demande;
use App\Form\DemandeType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DemandeController extends AbstractController
{
    private $entityManager;
    public function __construct(ManagerRegistry $entityManager){
        $this->entityManager = $entityManager;
    }
    #[Route('/demande', name: 'demande')]
    public function index(): Response
    {
        $user = $this->getUser();
        $demandes = $user->getDemandes();

        return $this->render('demande/index.html.twig', [
            'demandes' => $demandes,
        ]);
    }

    #[Route('/demande/creer', name: 'creer_demande')]
    public function add(Request $request): Response
    {
        $form = $this->createForm(DemandeType::class, null);
        $form->handleRequest($request);
        $doctrine =  $this->entityManager->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
            $dateCreation = new \DateTimeImmutable();
            $demande = new Demande();
            $demande->setTitre($form->get('titre')->getData());
            $demande->setContenu($form->get('contenu')->getData());
            $demande->setStatus($form->get('status')->getData());
            $demande->setDateCreation($dateCreation);
            $demande->setUser($this->getUser());
            $doctrine->persist($demande);
            $doctrine->flush();
        }
        return $this->render('demande/creer.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/demande/creer.html.twig
{% extends 'base.html.twig' %}
{% block title %}Demandes{% endblock %}

{% block content %}
    <h1>Créer une nouvelle demande</h1>

    {{ form(form) }}


{% endblock %}

templates/demande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demandes{% endblock %}


{% block content %}
        <a class="btn btn-info btn-lg float-right" href="{{ path('creer_demande') }}">
            Créer une nouvelle demande
        </a>
    <h1>Mes demandes</h1>
        {% if demandes|length > 0 %}
            <div class="table-responsive-lg">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Demande</th>
                    <th scope="col">Contenu</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Status</th>
                    <th scope="col">Pièce jointe</th>
                </tr>
                </thead>
                <tbody>
                {% for demande in demandes %}
                    <tr>

                        <td>{{ demande.titre }}</td>
                        <td>{{ demande.contenu}} </td>
                        <td>{{ demande.dateCreation|date('Y-m-d') }} à  {{ demande.dateCreation|date('H:m:s') }}</td>
                        <td>{{ demande.status.nom }} </td>
                        {% if demande.pieceJointe is defined and demande.pieceJointe %}
                        <td>
                            <a class='north' href="{{ asset(demande.pieceJointe) }}" target="_blank" title="Télecharger la pièce jointe">
                                <img class="piece-jointe center" src="{{ asset('assets/img/piece_jointe.png') }}" alt="Download file" />
                            </a>
                        </td>
                        {% endif %}


                    </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
            {% else %}
            <div class="text-center"><hr><h2>Aucune demande à afficher</h2></div>
        {% endif %}

{% endblock %}